package com.ues.too115.sistemabibliotecariomaven.models;
// Generated 11-24-2016 03:13:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Biblioteca generated by hbm2java
 */
public class Biblioteca  implements java.io.Serializable {


     private BigDecimal idbiblioteca;
     private String nombrebiblioteca;
     private String direccionbiblioteca;
     private BigDecimal telefenobiblioteca;
     private String paginaweb;
     private Set recursos = new HashSet(0);

    public Biblioteca() {
    }

	
    public Biblioteca(BigDecimal idbiblioteca, String nombrebiblioteca) {
        this.idbiblioteca = idbiblioteca;
        this.nombrebiblioteca = nombrebiblioteca;
    }
    public Biblioteca(BigDecimal idbiblioteca, String nombrebiblioteca, String direccionbiblioteca, BigDecimal telefenobiblioteca, String paginaweb, Set recursos) {
       this.idbiblioteca = idbiblioteca;
       this.nombrebiblioteca = nombrebiblioteca;
       this.direccionbiblioteca = direccionbiblioteca;
       this.telefenobiblioteca = telefenobiblioteca;
       this.paginaweb = paginaweb;
       this.recursos = recursos;
    }
   
    public BigDecimal getIdbiblioteca() {
        return this.idbiblioteca;
    }
    
    public void setIdbiblioteca(BigDecimal idbiblioteca) {
        this.idbiblioteca = idbiblioteca;
    }
    public String getNombrebiblioteca() {
        return this.nombrebiblioteca;
    }
    
    public void setNombrebiblioteca(String nombrebiblioteca) {
        this.nombrebiblioteca = nombrebiblioteca;
    }
    public String getDireccionbiblioteca() {
        return this.direccionbiblioteca;
    }
    
    public void setDireccionbiblioteca(String direccionbiblioteca) {
        this.direccionbiblioteca = direccionbiblioteca;
    }
    public BigDecimal getTelefenobiblioteca() {
        return this.telefenobiblioteca;
    }
    
    public void setTelefenobiblioteca(BigDecimal telefenobiblioteca) {
        this.telefenobiblioteca = telefenobiblioteca;
    }
    public String getPaginaweb() {
        return this.paginaweb;
    }
    
    public void setPaginaweb(String paginaweb) {
        this.paginaweb = paginaweb;
    }
    public Set getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set recursos) {
        this.recursos = recursos;
    }




}


