package com.ues.too115.sistemabibliotecariomaven.models;
// Generated 11-24-2016 03:13:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private BigDecimal idmunicipio;
     private Departamento departamento;
     private String nombremunicipio;
     private Set personas = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(BigDecimal idmunicipio, Departamento departamento, String nombremunicipio) {
        this.idmunicipio = idmunicipio;
        this.departamento = departamento;
        this.nombremunicipio = nombremunicipio;
    }
    public Municipio(BigDecimal idmunicipio, Departamento departamento, String nombremunicipio, Set personas) {
       this.idmunicipio = idmunicipio;
       this.departamento = departamento;
       this.nombremunicipio = nombremunicipio;
       this.personas = personas;
    }
   
    public BigDecimal getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(BigDecimal idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombremunicipio() {
        return this.nombremunicipio;
    }
    
    public void setNombremunicipio(String nombremunicipio) {
        this.nombremunicipio = nombremunicipio;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


