package com.ues.too115.sistemabibliotecariomaven.models;
// Generated 11-24-2016 03:13:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private BigDecimal idrecurso;
     private Subcategoria subcategoria;
     private Biblioteca biblioteca;
     private String nombrerecurso;
     private String descripcion;
     private String sinopsis;
     private String autores;
     private Date fecha;
     private BigDecimal volumen;
     private BigDecimal unidades;
     private String editorial;
     private String imagen;
     private String formato;
     private BigDecimal prestamointerno;
     private Set prestamos = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(BigDecimal idrecurso, Subcategoria subcategoria, Biblioteca biblioteca, String nombrerecurso, String descripcion, String autores, Date fecha, BigDecimal volumen, BigDecimal unidades, String editorial, String formato, BigDecimal prestamointerno) {
        this.idrecurso = idrecurso;
        this.subcategoria = subcategoria;
        this.biblioteca = biblioteca;
        this.nombrerecurso = nombrerecurso;
        this.descripcion = descripcion;
        this.autores = autores;
        this.fecha = fecha;
        this.volumen = volumen;
        this.unidades = unidades;
        this.editorial = editorial;
        this.formato = formato;
        this.prestamointerno = prestamointerno;
    }
    public Recurso(BigDecimal idrecurso, Subcategoria subcategoria, Biblioteca biblioteca, String nombrerecurso, String descripcion, String sinopsis, String autores, Date fecha, BigDecimal volumen, BigDecimal unidades, String editorial, String imagen, String formato, BigDecimal prestamointerno, Set prestamos) {
       this.idrecurso = idrecurso;
       this.subcategoria = subcategoria;
       this.biblioteca = biblioteca;
       this.nombrerecurso = nombrerecurso;
       this.descripcion = descripcion;
       this.sinopsis = sinopsis;
       this.autores = autores;
       this.fecha = fecha;
       this.volumen = volumen;
       this.unidades = unidades;
       this.editorial = editorial;
       this.imagen = imagen;
       this.formato = formato;
       this.prestamointerno = prestamointerno;
       this.prestamos = prestamos;
    }
   
    public BigDecimal getIdrecurso() {
        return this.idrecurso;
    }
    
    public void setIdrecurso(BigDecimal idrecurso) {
        this.idrecurso = idrecurso;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public Biblioteca getBiblioteca() {
        return this.biblioteca;
    }
    
    public void setBiblioteca(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
    }
    public String getNombrerecurso() {
        return this.nombrerecurso;
    }
    
    public void setNombrerecurso(String nombrerecurso) {
        this.nombrerecurso = nombrerecurso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public String getAutores() {
        return this.autores;
    }
    
    public void setAutores(String autores) {
        this.autores = autores;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getVolumen() {
        return this.volumen;
    }
    
    public void setVolumen(BigDecimal volumen) {
        this.volumen = volumen;
    }
    public BigDecimal getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(BigDecimal unidades) {
        this.unidades = unidades;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }
    public BigDecimal getPrestamointerno() {
        return this.prestamointerno;
    }
    
    public void setPrestamointerno(BigDecimal prestamointerno) {
        this.prestamointerno = prestamointerno;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


